triggers:
- envs: []
  name: homework2_trigger
  pipeline_uuid: homework_2
  schedule_interval: 00 05 * * *
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-05 05:00:00
  status: active
  variables: {}
